export const districtData = {
  Dhaka: [
    "Dhanmondi",
    "Mohammadpur",
    "Mirpur",
    "Uttara",
    "Gulshan",
    "Banani",
    "Badda",
    "Khilgaon",
    "Ramna",
    "Tejgaon",
    "Savar",
    "Keraniganj",
    "Nawabganj",
    "Dohar",
  ],

  Tangail: [
    "Tangail Sadar",
    "Basail",
    "Bhuapur",
    "Delduar",
    "Ghatail",
    "Gopalpur",
    "Kalihati",
    "Madhupur",
    "Mirzapur",
    "Nagarpur",
    "Sakhipur",
    "Dhanbari",
  ],

  Gazipur: [
    "Gazipur Sadar",
    "Kaliakoir",
    "Kapasia",
    "Sreepur",
    "Kaliganj",
    "Tongi",
  ],

  Mymensingh: [
    "Mymensingh Sadar",
    "Bhaluka",
    "Muktagacha",
    "Trishal",
    "Gafargaon",
    "Phulpur",
    "Fulbaria",
    "Ishwarganj",
    "Nandail",
    "Haluaghat",
    "Dhobaura",
    "Gouripur",
    "Tarakanda",
  ],

  Chattogram: [
    "Kotwali",
    "Pahartali",
    "Panchlaish",
    "Halishahar",
    "Patenga",
    "Chandgaon",
    "Bayezid",
    "Double Mooring",
  ],

  Cumilla: [
    "Cumilla Sadar",
    "Burichang",
    "Chandina",
    "Daudkandi",
    "Debidwar",
    "Laksam",
    "Muradnagar",
    "Meghna",
  ],

  Rajshahi: [
    "Boalia",
    "Rajpara",
    "Motihar",
    "Paba",
    "Godagari",
    "Bagha",
    "Bagmara",
    "Tanore",
    "Durgapur",
    "Charghat",
    "Puthia",
  ],

  Khulna: [
    "Sonadanga",
    "Khalishpur",
    "Daulatpur",
    "Kotwali",
    "Rupsha",
    "Dumuria",
    "Paikgacha",
    "Batiaghata",
    "Terokhada",
    "Dighalia",
    "Koyra",
  ],

  Barishal: [
    "Barishal Sadar",
    "Bakerganj",
    "Banaripara",
    "Babuganj",
    "Agailjhara",
    "Mehendiganj",
    "Muladi",
    "Wazirpur",
  ],

  Sylhet: [
    "Sylhet Sadar",
    "Beanibazar",
    "Golapganj",
    "Zakiganj",
    "Balaganj",
    "Companiganj",
    "Kanaighat",
    "Jaintiapur",
  ],

  Rangpur: [
    "Rangpur Sadar",
    "Badarganj",
    "Gangachara",
    "Kaunia",
    "Mithapukur",
    "Pirgacha",
    "Pirganj",
    "Taraganj",
  ],

  Dinajpur: [
    "Dinajpur Sadar",
    "Birampur",
    "Birganj",
    "Bochaganj",
    "Chirirbandar",
    "Fulbari",
    "Hakimpur",
    "Kaharol",
    "Khansama",
    "Nawabganj",
    "Parbatipur",
  ],

  Noakhali: [
    "Noakhali Sadar",
    "Begumganj",
    "Chatkhil",
    "Companiganj",
    "Hatia",
    "Kabirhat",
    "Senbagh",
    "Subarnachar",
  ],

  "Cox's Bazar": [
  "Cox's Bazar Sadar",
  "Chakaria",
  "Kutubdia",
  "Maheshkhali",
  "Pekua",
  "Ramu",
  "Teknaf",
  "Ukhia",
],
};
export default districtData;